server:
  port: 8080

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://${ACADEMIC_DB_HOST}:${ACADEMIC_DB_PORT}/${ACADEMIC_DB}?createDatabaseIfNotExist=true
    username: ${ACADEMIC_DB_USER}
    password: ${ACADEMIC_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  rabbitmq:
    addresses: ${RABBIT_ADDRESS}
  application:
    name: academic-service

rabbitMQ:
  exchanges:
    internal: internal.exchange
  queues:
    student-notification: student.notification.queue
    student-notification-pre: student.notification.pre.queue
  routing-keys:
    internal-student-notification: internal.student.notification.routing-key
    internal-student-notification-pre: internal.student.notification.pre.routing-key

logging:
  level:
    com:
      school:
        academic: debug