server:
  port: 8081

spring:
  web:
    resources:
      add-mappings: false
  application:
    name: finance-service
  data:
    mongodb:
      host: ${FINANCE_DB_HOST}
      port: ${FINANCE_DB_PORT}
      database: ${FINANCE_DB}
      username: ${FINANCE_DB_USER}
      password: ${FINANCE_DB_PASS}

rabbitMQ:
  exchanges:
    internal: internal.exchange
  queues:
    student-notification: student.notification.queue
    student-notification-pre: student.notification.pre.queue
    student-notification-trans : student.notification.trans.queue
  routing-keys:
    internal-student-notification: internal.student.notification.routing-key
    internal-student-notification-pre: internal.student.notification.pre.routing-key
    internal-student-notification-trans : internal.student.notification.trans.routing-key

logging:
  level:
    com:
      school:
        finance: debug

finance:
  point-cost: 1000