server:
  port: 8081

spring:
  web:
    resources:
      add-mappings: false
  application:
    name: finance-service
  data:
    mongodb:
      host: ${FINANCE_DB_HOST}
      port: ${FINANCE_DB_PORT}
      database: ${FINANCE_DB}
      username: ${FINANCE_DB_USER}
      password: ${FINANCE_DB_PASS}

logging:
  level:
    com:
      school:
        finance: debug

finance:
  point-cost: 1000